"""
Release Package Generator
Creates ZIP packages with redacted documents and cover letters
"""

import io
import logging
import zipfile
from datetime import datetime

from jinja2 import Template

logger = logging.getLogger(__name__)

# Cover letter template
COVER_LETTER_TEMPLATE = """
FREEDOM OF INFORMATION REQUEST
Response Letter

Date: {{ date }}
Case Number: {{ case_number }}
Requester: {{ requester_name }}

Dear {{ requester_name }},

Re: Freedom of Information Request - {{ case_title }}

This letter is in response to your Freedom of Information request received on {{ request_date }}.

DECISION

{% if released_count > 0 %}
We are releasing {{ released_count }} document(s) in response to your request.
{% endif %}

{% if withheld_count > 0 %}
We are withholding {{ withheld_count }} document(s) in full or in part under the following exemptions:
{% endif %}

DOCUMENTS RELEASED

{% for doc in released_documents %}
{{ loop.index }}. {{ doc.filename }}
   {% if doc.redaction_count > 0 %}
   - Redacted under: {{ doc.exemptions|join(', ') }}
   {% else %}
   - Released in full
   {% endif %}
{% endfor %}

{% if withheld_documents %}
DOCUMENTS WITHHELD

{% for doc in withheld_documents %}
{{ loop.index }}. {{ doc.filename }}
   - Withheld under: {{ doc.exemptions|join(', ') }}
   - Reason: {{ doc.reason }}
{% endfor %}
{% endif %}

EXEMPTIONS APPLIED

{% for exemption, description in exemptions.items() %}
{{ exemption }}: {{ description }}
{% endfor %}

RIGHT TO REVIEW

If you are not satisfied with this response, you have the right to request a review by the Information and Privacy Commissioner within 30 days of receiving this letter.

Sincerely,

{{ officer_name }}
{{ officer_title }}
Freedom of Information Officer

---
Generated by BlackBar FOI Management System
{{ generation_date }}
"""


def generate_cover_letter(case_data: dict, documents: list[dict]) -> str:
    """
    Generate a cover letter for the release package.

    Args:
        case_data: Case information
        documents: List of documents with status and exemptions

    Returns:
        Cover letter text
    """
    template = Template(COVER_LETTER_TEMPLATE)

    # Separate released and withheld documents
    released_docs = [d for d in documents if d.get("status") in ["released", "approved"]]
    withheld_docs = [d for d in documents if d.get("status") == "withheld"]

    # Collect all exemptions used
    exemptions = {}
    for doc in documents:
        for exemption in doc.get("exemptions", []):
            if exemption not in exemptions:
                exemptions[exemption] = get_exemption_description(exemption)

    # Render template
    letter = template.render(
        date=datetime.now().strftime("%B %d, %Y"),
        case_number=case_data.get("case_number", "N/A"),
        case_title=case_data.get("title", "N/A"),
        requester_name=case_data.get("requester_name", "Requester"),
        request_date=case_data.get("created_at", "N/A"),
        released_count=len(released_docs),
        withheld_count=len(withheld_docs),
        released_documents=released_docs,
        withheld_documents=withheld_docs,
        exemptions=exemptions,
        officer_name=case_data.get("officer_name", "FOI Officer"),
        officer_title=case_data.get("officer_title", "Information Officer"),
        generation_date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    )

    return letter


def get_exemption_description(exemption_code: str) -> str:
    """Get description for exemption code."""
    descriptions = {
        "S13": "Policy advice or recommendations",
        "S14": "Solicitor-client privilege",
        "S15": "Harm to law enforcement",
        "S16": "Harm to intergovernmental relations",
        "S17": "Harm to financial or economic interests",
        "S18": "Harm to conservation",
        "S19": "Harm to individual or public safety",
        "S20": "Harm to security of property",
        "S21": "Harm to business interests of third party",
        "S22": "Personal information",
        "S23": "Harm to local government confidences",
    }
    return descriptions.get(exemption_code, "Exemption applied")


def create_release_package(
    case_data: dict, documents: list[dict], include_cover_letter: bool = True
) -> bytes:
    """
    Create a ZIP package with redacted documents and cover letter.

    Args:
        case_data: Case information
        documents: List of documents with content and metadata
        include_cover_letter: Whether to include cover letter

    Returns:
        ZIP file as bytes
    """
    try:
        # Create ZIP in memory
        zip_buffer = io.BytesIO()

        with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
            # Add cover letter
            if include_cover_letter:
                cover_letter = generate_cover_letter(case_data, documents)
                zip_file.writestr("00_COVER_LETTER.txt", cover_letter)

            # Add release summary
            summary = generate_release_summary(case_data, documents)
            zip_file.writestr("00_RELEASE_SUMMARY.txt", summary)

            # Add documents
            for i, doc in enumerate(documents, 1):
                if doc.get("status") in ["released", "approved"]:
                    # Add redacted document
                    filename = f"{i:02d}_{doc.get('filename', 'document.pdf')}"
                    content = doc.get("redacted_content") or doc.get("content")

                    if content:
                        zip_file.writestr(filename, content)
                    else:
                        logger.warning(f"No content for document: {doc.get('filename')}")

        # Get ZIP bytes
        zip_bytes = zip_buffer.getvalue()
        zip_buffer.close()

        logger.info(f"Created release package with {len(documents)} documents")
        return zip_bytes

    except Exception as e:
        logger.error(f"Error creating release package: {str(e)}")
        raise Exception(f"Failed to create release package: {str(e)}")


def generate_release_summary(case_data: dict, documents: list[dict]) -> str:
    """Generate a summary of the release."""
    released = [d for d in documents if d.get("status") in ["released", "approved"]]
    withheld = [d for d in documents if d.get("status") == "withheld"]

    summary = f"""
RELEASE PACKAGE SUMMARY
=======================

Case Number: {case_data.get("case_number", "N/A")}
Case Title: {case_data.get("title", "N/A")}
Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

STATISTICS
----------
Total Documents: {len(documents)}
Released: {len(released)}
Withheld: {len(withheld)}

RELEASED DOCUMENTS
------------------
"""

    for i, doc in enumerate(released, 1):
        redaction_count = doc.get("redaction_count", 0)
        summary += f"{i}. {doc.get('filename')}\n"
        if redaction_count > 0:
            summary += f"   Redactions: {redaction_count}\n"
            summary += f"   Exemptions: {', '.join(doc.get('exemptions', []))}\n"

    if withheld:
        summary += "\nWITHHELD DOCUMENTS\n------------------\n"
        for i, doc in enumerate(withheld, 1):
            summary += f"{i}. {doc.get('filename')}\n"
            summary += f"   Reason: {doc.get('reason', 'N/A')}\n"

    summary += "\n---\nGenerated by BlackBar FOI Management System\n"

    return summary
